### ISSUE TITLE
copy the ancestral file to ancestral param rather than pop

### ISSUE THREAD

**Issue by lonelyjoeparker** [jnarag/teaspoon#27]
e.g. analyse the 'first' timepoint as both the (consensus-defining) ancestral alignment, and as a mainfile in its own right
decide later how to toggle this - for now, just default to analysing all files in fileslist as 'main'

**Comment by lonelyjoeparker** [comment]
Hi @jnarag quick question on this one, binary choice:

(option 1) Presumably when inferring a neutral ratio with either aggregated or averaged methods, you want the zeroth timepoint/'ancestral'/'outgroup' alignment to be included in this step too?

(option 2) At the moment all we use the ancestral for is to get a consensus, then the 1-th > n-th timepoints are the ones used in the inference procedure.

**Comment by jnarag** [comment]
Hi Joe, 

I would think the option 1 is more elegant, and in most situations we shouldn’t expect many mid or high freq polymorphisms at the zeroth time point. However, we should confirm with Oli this implementation makes sense. 

Jayna

**Comment by lonelyjoeparker** [comment]
OK no worries. Are you likely to see him this week?

**Comment by jnarag** [comment]
Unlikely to see him this week. 

However, after thinking about this some more - we probably should start the “main analysis” from the 1st timepoint rather than zeroth timepoint. 

I checked my test files, which are all consistent with this approach, so rather than introduce anything unusual at this stage, we should probably stick with the original analysis. 

Sorry for making you do this unnecessary change. I guess if someone wants to include the the zeroth timepoint, they could in theory have a duplicate fasta file with a different name? 

Jayna

**Comment by lonelyjoeparker** [comment]
No that's ok - it was a small one anyway and I hadn't committed anything, so I'll just reset HEAD.

Closing #27

**Comment by lonelyjoeparker** [comment]
Thx for checking!

**Comment by jnarag** [comment]
Glad it was only a minor change.
